### ISSUE TITLE
 mailstream_ssl_context is inaccessable

### ISSUE THREAD

**Issue by Dunemaster** [dinhviethoa/libetpan#170]
Using parameter ssl_context in callback function for mailpop3_ssl_connect_with_callback is not possible, as struct mailstream_ssl_context is defined in mailstream_ssl.c, not in a public header.

Consider, please, moving  struct mailstream_ssl_context  definition to a public header

**Comment by dinhviethoa** [comment]
Actually, mailstream_ssl_get_openssl_ssl_ctx() is already available.
```
void * mailstream_ssl_get_openssl_ssl_ctx(struct mailstream_ssl_context * ssl_context)
```
