### ISSUE TITLE
mailmime_encoded_phrase_parse could support additional wrong encoding

### ISSUE THREAD

**Issue by 77tb** [dinhviethoa/libetpan#173]
To: 
	"=?UTF-8?B?5ZOO5ZGA5oiR5Y676IGU57O75Lq65ZCN5a2X6L+Y6IO96L+Z5LmI6ZW/5ZGi?= =?UTF-8?B?5ZOO5ZGA5oiR5Y676IGU57O75Lq65ZCN5a2X6L+Y6IO96L+Z5LmI6ZW/5ZGi?=" <260919069@qq.com>

**Comment by pitiphong-p** [comment]
I think I found the cause of the bug. The algorithm in `mailmime_encoded_phrase_parse` function is wrong. Currently this function will extract the encoded data and then decode the encoded data line by line and then concatenate the result in the end. I think the correct way is we need to extract the encoded data every line concatenate the encoded data then decode it at last.

**Comment by dinhviethoa** [comment]
Could you show me the result of libetpan and what you're expecting? Thanks.

**Comment by pitiphong-p** [comment]
Subject: =?UTF-8?B?4Lij4Liw4LmA4Lia4Li04LiU4LiE4Lin4Liy4Lih4Lih4Lix4LiZ4Liq4LmM?=
 =?UTF-8?B?4LmA4LiV4LmH4Lih4Lie4Li04LiB4Lix4LiUIFRSQU5TRk9STUVSUyA0IOC4?=
 =?UTF-8?B?oeC4seC4meC4quC5jOC4hOC4o+C4muC4l+C4uOC4geC4o+C4sOC4muC4miDg?=
 =?UTF-8?B?uJfguLXguYjguYDguJTguLXguKLguKfguYPguJnguYDguKHguLfguK3guIfg?=
 =?UTF-8?B?uYTguJfguKI=?=

Expected result: ระเบิดความมันส์เต็มพิกัด TRANSFORMERS 4 มันส์ครบทุกระบบ ที่เดียวในเมืองไทย
libetpan result: ระเบิดความมันส์เต็มพิกัด TRANSFORMERS 4 ?ันส์ครบทุกระบบ ??ี่เดียวในเมือง??ทย

**Comment by dinhviethoa** [comment]
I think MIME RFC (RFC 2047) is describing each item as "encoded word" and therefore, each word should be decoded separately.
Then, `mailmime_encoded_phrase_parse` has the correct behavior.

Of course, it could be improved to support wrong encoding such as the one you shown here.

**Comment by pitiphong-p** [comment]
Each Thai character needs 3 bytes in UTF-8 encoding. I think some character might be encoded into two lines so when you decode the data line by line, we will get incomplete character UTF-8 data.
So I think we should combine the encoded data into 1 line first then decode them in the end.

**Comment by dinhviethoa** [comment]
Sure. That's what happen for wrong MIME encoding.
Proper MIME encoding won't break a character on several two lines.

And of course, a good improvement would be to take care of those wrong encoding.

**Comment by pitiphong-p** [comment]
Just read the RFC in detail about encoded-word.
That's great. Do you have any plan on this one yet?

**Comment by dinhviethoa** [comment]
I don't. If you have some implementation in mind of how to fix it, you could send a pull request.
Keep in mind that encoding for the words could be different.

**Comment by pitiphong-p** [comment]
im not sue what do you mean that encoding for the words could be different?

**Comment by dinhviethoa** [comment]
I meant the charset encoding: `(=?ISO-8859-1?Q?a?= =?ISO-8859-2?Q?_b?=)`

**Comment by pitiphong-p** [comment]
I see. I still don't have any idea on the fix now. Need some time to think about it though.
