### ISSUE TITLE
Prebuild step fails on Visual Studio 2013

### ISSUE THREAD

**Issue by fcoulombegoogle** [dinhviethoa/libetpan#185]
it's trying to copy the file "src\main\libetpan_version.h" which no longer exists.

**Comment by dinhviethoa** [comment]
Were you able to build libetpan eventually?

**Comment by fcoulombegoogle** [comment]
nope, i'm getting "../../third-party/lib\libsasl2.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2C0"

**Comment by dinhviethoa** [comment]
I'm not sure why it's not looking for libsasl2.lib instead.

**Comment by fcoulombegoogle** [comment]
because the linker line says the equivalent of -llibsasl2.dll :)
it should probably try to link against the .lib version. a typo

**Comment by dinhviethoa** [comment]
Fixed with #191.
