### ISSUE TITLE
libetpan-config.h redefines "inline" which is against the standard.

### ISSUE THREAD

**Issue by fcoulombegoogle** [dinhviethoa/libetpan#189]
libetpan-config.h.in:13 --> @	define inline __inline
libetpan-config.h:83 --> #	define inline __inline

this is preprocessed to only happen on visual studio.
as far as visual studio is concerned, inline and __inline are the same and are both supported.

This might have come from some old visual studio version (vc6?) which didn't at the time officially supported inline and only had __inline. either way... VS2013 is now free, so I believe open source projects should gear themselves toward that version of the product. Anyone stuck on vc6 should really be considered as a minority (like trying to support windows 98)

**Comment by fcoulombegoogle** [comment]
further investigation made me realize that inline is not available in Visual C which is why this code was there at the first place and that the code should be preprocessed out ifdef cplusplus

**Comment by dinhviethoa** [comment]
Should I close it then?  

--  
Hoa V. Dinh

**Comment by fcoulombegoogle** [comment]
no, there's a patch for this. Right now it builds in C but not in C++ and this is a public header that gets included into C++.
Will send a pull request.
