### ISSUE TITLE
Ill OS detection within mailsmtp.c breaks building on cygwin (and further other *nices).

### ISSUE THREAD

**Issue by persmule** [dinhviethoa/libetpan#201]
In mailsmtp.c, `__linux__` and `WIN32` is used to detect the lack of `sockaddr::sa_len` (forgive me for this c++-flavor notation), but in reality, `sockaddr::sa_len` only exists on BSD-derived unices and is absent on most operating systems, further more, a flag `_HAVE_SA_LEN` should be present to indicate its existence.
So I believe the related code should be like this:
```diff
diff --git a/src/low-level/smtp/mailsmtp.c b/src/low-level/smtp/mailsmtp.c
index 727e6e4..8076f9d 100644
--- a/src/low-level/smtp/mailsmtp.c
+++ b/src/low-level/smtp/mailsmtp.c
@@ -276,10 +276,10 @@ static int get_hostname(mailsmtp * session, int useip, char * buf, int len)
     if (r != 0)
       return MAILSMTP_ERROR_HOSTNAME;
 
-#if (defined __linux__ || defined WIN32)
-    r = getnameinfo(&addr, sizeof(addr), hostname, HOSTNAME_SIZE, NULL, 0, NI_NUMERICHOST);
-#else
+#if (defined _HAVE_SA_LEN /*For *BSD*/|| defined __APPLE__ /*The ROTTEN Apples do have sa_len but lack _HAVE_SA_LEN*/)
     r = getnameinfo(&addr, addr.sa_len, hostname, HOSTNAME_SIZE, NULL, 0, NI_NUMERICHOST);
+#else //For other *nices (include Cygwin) and M$WIN
+    r = getnameinfo(&addr, sizeof(addr), hostname, HOSTNAME_SIZE, NULL, 0, NI_NUMERICHOST);
 #endif
     if (r != 0)
       return MAILSMTP_ERROR_HOSTNAME;
```
With this patch it can be built on Cygwin and most unices. Please consider to apply this for better portability.
Best regard.

**Comment by dinhviethoa** [comment]
Thanks. I'll take a look.

**Comment by dinhviethoa** [comment]
Maybe you could submit a pull request (but remove the opinionated comment)?

**Comment by persmule** [comment]
Sorry, I do not think I must fork your whole project only to file a bug related to only one file. If you don't like those opinionated comment, just remove them.

**Comment by persmule** [comment]
And that Cygwin building is actually not mine. I just noticeed it when it is being built.
