### ISSUE TITLE
Fails to build on XCode 7 beta 5.

### ISSUE THREAD

**Issue by navisingh** [dinhviethoa/libetpan#209]
This is when building for iOS 9 for a physical device as opposed to the simulator.

ExternalBuildToolExecution libetpan-prepare-ios
    cd /Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac
    export ACTION=
    export ALTERNATE_GROUP=staff
    export ALTERNATE_MODE=u+w,go-w,a+rX
    export ALTERNATE_OWNER=navisingh
    export ALWAYS_SEARCH_USER_PATHS=YES
    export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY=NO
    export APPLY_RULES_IN_COPY_FILES=NO
    export ARCHS=x86_64
    export AVAILABLE_PLATFORMS="iphonesimulator macosx watchsimulator iphoneos watchos"
    export BITCODE_GENERATION_MODE=marker
    export BUILD_ACTIVE_RESOURCES_ONLY=YES
    export BUILD_COMPONENTS="headers build"
    export BUILD_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products
    export BUILD_ROOT=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products
    export BUILD_STYLE=
    export BUILD_VARIANTS=normal
    export BUILT_PRODUCTS_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products/Debug-iphonesimulator
    export CACHE_ROOT=/var/folders/qq/8dy897hx03vbwmqhpcpvq98h0000gn/C/com.apple.DeveloperTools/7.0-7A176x/Xcode
    export CLANG_ANALYZER_DEADCODE_DEADSTORES=NO
    export CLANG_MODULES_BUILD_SESSION_FILE=/Users/navisingh/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation
    export CLASS_FILE_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build/JavaClasses
    export CLONE_HEADERS=NO
    export CODE_SIGNING_ALLOWED=NO
    export COLOR_DIAGNOSTICS=NO
    export CONFIGURATION=Debug
    export CONFIGURATION_BUILD_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products/Debug-iphonesimulator
    export CONFIGURATION_TEMP_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator
    export COPYING_PRESERVES_HFS_DATA=NO
    export COPY_HEADERS_RUN_UNIFDEF=NO
    export COPY_PHASE_STRIP=YES
    export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
    export DEAD_CODE_STRIPPING=NO
    export DEBUGGING_SYMBOLS=YES
    export DEBUG_INFORMATION_FORMAT=dwarf-with-dsym
    export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
    export DEFINES_MODULE=NO
    export DEPLOYMENT_LOCATION=NO
    export DEPLOYMENT_POSTPROCESSING=NO
    export DERIVED_FILES_DIR=
    export DERIVED_FILE_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build/DerivedSources
    export DERIVED_SOURCES_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode-beta.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR=/Applications/Xcode-beta.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR=/Applications/Xcode-beta.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR=/Applications/Xcode-beta.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR=/Applications/Xcode-beta.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR=/Applications/Xcode-beta.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE=English
    export DO_HEADER_SCANNING_IN_JAM=NO
    export DSTROOT=/tmp/libetpan.dst
    export DT_TOOLCHAIN_DIR=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME=.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
    export DWARF_DSYM_FOLDER_PATH=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products/Debug-iphonesimulator
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
    export ENABLE_BITCODE=NO
    export ENABLE_HEADER_DEPENDENCIES=YES
    export ENABLE_ON_DEMAND_RESOURCES=NO
    export ENABLE_TESTABILITY=YES
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
    export FILE_LIST=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build/Objects/LinkFileList
    export FRAMEWORK_VERSION=A
    export GCC3_VERSION=3.3
    export GCC_C_LANGUAGE_STANDARD=c99
    export GCC_OPTIMIZATION_LEVEL=0
    export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1 "
    export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
    export GCC_WARN_ABOUT_RETURN_TYPE=YES
    export GCC_WARN_UNUSED_VARIABLE=YES
    export GENERATE_MASTER_OBJECT_FILE=NO
    export GENERATE_PKGINFO_FILE=NO
    export GENERATE_PROFILING_CODE=NO
    export GID=20
    export GROUP=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
    export HEADERMAP_USES_VFS=NO
    export HEADER_SEARCH_PATHS="/Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac/.. /Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac/include"
    export HIDE_BITCODE_SYMBOLS=YES
    export HOME=/Users/navisingh
    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
    export INFOPLIST_OUTPUT_FORMAT=binary
    export INFOPLIST_PREPROCESS=NO
    export INSTALL_DIR=/tmp/libetpan.dst
    export INSTALL_GROUP=staff
    export INSTALL_MODE_FLAG=u+w,go-w,a+rX
    export INSTALL_OWNER=navisingh
    export INSTALL_ROOT=/tmp/libetpan.dst
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES=YES
    export JAVA_ARCHIVE_TYPE=JAR
    export JAVA_COMPILER=/usr/bin/javac
    export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
    export JAVA_JAR_FLAGS=cv
    export JAVA_SOURCE_SUBDIR=.
    export JAVA_USE_DEPENDENCIES=YES
    export JAVA_ZIP_FLAGS=-urg
    export KEEP_PRIVATE_EXTERNS=NO
    export LD_DEPENDENCY_INFO_FILE=//_dependency_info.dat
    export LD_GENERATE_MAP_FILE=NO
    export LD_MAP_FILE_PATH=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build/-LinkMap--.txt
    export LD_NO_PIE=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
    export LEGACY_DEVELOPER_DIR=/Applications/Xcode-beta.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LIBRARY_FLAG_NOSPACE=YES
    export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
    export LINKER_DISPLAYS_MANGLED_NAMES=NO
    export LINK_WITH_STANDARD_LIBRARIES=YES
    export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
    export LOCAL_APPS_DIR=/Applications
    export LOCAL_DEVELOPER_DIR=/Library/Developer
    export LOCAL_LIBRARY_DIR=/Library
    export MAC_OS_X_PRODUCT_BUILD_VERSION=14E46
    export MAC_OS_X_VERSION_ACTUAL=101004
    export MAC_OS_X_VERSION_MAJOR=101000
    export MAC_OS_X_VERSION_MINOR=1004
    export MODULE_CACHE_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/ModuleCache
    export OBJECT_FILE_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build/Objects
    export OBJROOT=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates
    export ONLY_ACTIVE_ARCH=YES
    export OPTIMIZATION_LEVEL=0
    export OS=MACOS
    export OTHER_CFLAGS="-DHAVE_CFNETWORK=1 -DHAVE_CONFIG_H=1"
    export OTHER_CPLUSPLUSFLAGS="-DHAVE_CFNETWORK=1 -DHAVE_CONFIG_H=1"
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode-beta.app/Contents/Developer/Headers /Applications/Xcode-beta.app/Contents/Developer/SDKs /Applications/Xcode-beta.app/Contents/Developer/Platforms"
    export PLATFORM_NAME=iphonesimulator
    export PLIST_FILE_OUTPUT_FORMAT=binary
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
    export PRECOMP_DESTINATION_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
    export PRODUCT_NAME=
    export PROFILING_CODE=NO
    export PROJECT=libetpan
    export PROJECT_DERIVED_FILE_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/DerivedSources
    export PROJECT_DIR=/Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac
    export PROJECT_FILE_PATH=/Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac/libetpan.xcodeproj
    export PROJECT_NAME=libetpan
    export PROJECT_TEMP_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build
    export PROJECT_TEMP_ROOT=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates
    export REMOVE_CVS_FROM_RESOURCES=YES
    export REMOVE_GIT_FROM_RESOURCES=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
    export REMOVE_HG_FROM_RESOURCES=YES
    export REMOVE_SVN_FROM_RESOURCES=YES
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
    export SDKROOT=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk
    export SEPARATE_STRIP=NO
    export SEPARATE_SYMBOL_EDIT=NO
    export SHARED_DERIVED_FILE_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products/Debug-iphonesimulator/DerivedSources
    export SHARED_PRECOMPS_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/PrecompiledHeaders
    export SKIP_INSTALL=YES
    export SOURCE_ROOT=/Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac
    export SRCROOT=/Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac
    export STRINGS_FILE_OUTPUT_ENCODING=binary
    export STRIP_BITCODE_FROM_COPIED_FILES=NO
    export STRIP_INSTALLED_PRODUCT=YES
    export STRIP_STYLE=all
    export SUPPORTED_PLATFORMS="iphonesimulator iphoneos"
    export SUPPORTS_TEXT_BASED_API=NO
    export SYMROOT=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products
    export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
    export SYSTEM_APPS_DIR=/Applications
    export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode-beta.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode-beta.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode-beta.app/Contents/Developer/Applications/Utilities/Built Examples"
    export SYSTEM_DEVELOPER_DIR=/Applications/Xcode-beta.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode-beta.app/Contents/Developer/ADC Reference Library"
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode-beta.app/Contents/Developer/Applications/Graphics Tools"
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode-beta.app/Contents/Developer/Applications/Java Tools"
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode-beta.app/Contents/Developer/Applications/Performance Tools"
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode-beta.app/Contents/Developer/ADC Reference Library/releasenotes"
    export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode-beta.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode-beta.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode-beta.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
    export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode-beta.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode-beta.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR=/System/Library
    export TARGETNAME=libetpan-prepare-ios
    export TARGET_BUILD_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products/Debug-iphonesimulator
    export TARGET_DEVICE_MODEL=iPhone7,2
    export TARGET_DEVICE_OS_VERSION=8.4
    export TARGET_NAME=libetpan-prepare-ios
    export TARGET_TEMP_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build
    export TEMP_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build
    export TEMP_FILES_DIR=
    export TEMP_FILE_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates/libetpan.build/Debug-iphonesimulator/libetpan-prepare-ios.build
    export TEMP_ROOT=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Intermediates
    export TOOLCHAINS=com.apple.dt.toolchain.iOS9_0
    export TOOLCHAIN_DIR=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
    export UID=501
    export USER=navisingh
    export USER_APPS_DIR=/Users/navisingh/Applications
    export USER_LIBRARY_DIR=/Users/navisingh/Library
    export USE_HEADERMAP=YES
    export WATCH_BUILT_PRODUCTS_DIR=/Users/navisingh/Library/Developer/Xcode/DerivedData/Tipbit-fpktqofolsioikezivmzoddxfsnp/Build/Products/Debug-watchsimulator
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode-beta.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=7A176x
    export XCODE_VERSION_ACTUAL=0700
    export XCODE_VERSION_MAJOR=0700
    export XCODE_VERSION_MINOR=0700
    export arch=x86_64
    export variant=normal
    /bin/sh /Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac/update.sh

+ test '!' -d libetpan.xcodeproj
++ pwd
+ logfile=/Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac/update.log
+ cd ..
+ test x = xprepare
+ test x = xprepare-clean
+ test x/Users/navisingh/Documents/_git/tb/MailCore/libetpan/build-mac = x
+ test x = x
+ ACTION=build
+ test xbuild = xbuild
+ md5 build-mac/autogen-result.tar.gz
+ cmp -s build-mac/autogen-result.md5 build-mac/autogen-result.md5.new
+ rm -f build-mac/autogen-result.md5.new
+ test '!' -f Makefile
+ test xiphonesimulator = xiphoneos -o xiphonesimulator = xiphonesimulator
+ test '!' -d build-mac/libsasl-ios
+ cd build-mac
+ sh ./prepare-ios.sh
running prepare-cyrus-sasl.sh
prepare sources
patching file lib/client.c
building tools
generated makemd5i386 properly
building for iPhoneOS - armv7
CONFIGURE FAILED
Command /bin/sh failed with exit code 1

**Comment by ewanmellor** [comment]
Fixed by PR #210.
