### ISSUE TITLE
Prefix MD5 functions ( issue on StackOverflow )

### ISSUE THREAD

**Issue by bunkerbilly** [dinhviethoa/libetpan#215]
I have just imported MailCore2 into my project and I have followed all the steps that they have stated, but I am still getting an issue.

duplicate symbol _hmac_md5_final in:

XYZ/Debug-iphonesimulator/libetpan-ios.a(md5.o)
ABC/libs/libsmbclient.a(hmacmd5.o) 
duplicate symbol _hmac_md5 in:

XYZ/Debug-iphonesimulator/libetpan-ios.a(md5.o)
ABC/libs/libsmbclient.a(hmacmd5.o) ld: 2 duplicate symbols for architecture x86_64

**Comment by dinhviethoa** [comment]
Fixed with 52f2806b7573b33bbc55df7849605da65e546fbd.
