### ISSUE TITLE
mailmime_encoded_phrase_parse cause crash

### ISSUE THREAD

**Issue by 77tb** [dinhviethoa/libetpan#219]
mailmime_encoded_phrase_parse is defined as:

LIBETPAN_EXPORT
int mailmime_encoded_phrase_parse(const char * default_fromcode,
    const char * message, size_t length,
    size_t * indx, const char * tocode,
    char ** result)

If |message| is a C-style string of "=?GBK?B??=" , the function will cause a crash.

**Comment by dinhviethoa** [comment]
It may be due to a recent change. I'll investigate. Thanks for reporting the issue!

**Comment by 77tb** [comment]
@dinhviethoa 

Great! Thx.
