### ISSUE TITLE
Is there no way to define a timeout on connect?

### ISSUE THREAD

**Issue by MacGritsch** [dinhviethoa/libetpan#220]
Hi,

if i specify "google.com" as the host and port 25, it tries to connect but cant connect (there is no service at port 25), but it does not return after 10 or 30 seconds, it returns after 5 minutes or so.
It would make sense to add a timeout right?

As I am working on OS X, I checked the implementation and saw that it uses CFStringCreateWithCString. If it is replaced with CFSocketCreateConnectedToSocketSignature a timeout would be possible (yes, I know, there are a few changes to do like converting the address to data and so on).

what do you think?

thank you

**Comment by dinhviethoa** [comment]
Which API are you using?
There's couple of _set_timeout calls on the APIs.
Do they have the intented behavior?

**Comment by MacGritsch** [comment]
I am using mailsmtp_ssl_connect() and mailsmtp_socket_connect().
If I set mailstream_network_delay to 2 seconds, the timeout is 22 sec, if I set it to 3 seconds its 33 seconds, and for 10 seconds its 110 seconds (always my value times 11).
But I see that I have not the newest code, so will test this tomorrow with the newest source code.

**Comment by dinhviethoa** [comment]
Please give mailsmtp_set_timeout() a try.
