### ISSUE TITLE
libcurl and libexpat disabled by default in a wrong way

### ISSUE THREAD

**Issue by mschwendt** [dinhviethoa/libetpan#221]
Just noticed the issue tracker is open after I had left a comment on configure.ac. It accidentally disables libcurl and libexpat by default. Here's the fix:

diff -Nurb --strip-trailing-cr libetpan-1.6-orig/configure.ac libetpan-1.6/configure.ac
--- libetpan-1.6-orig/configure.ac      2014-10-31 22:41:02.000000000 +0100
+++ libetpan-1.6/configure.ac   2016-01-30 02:52:28.121602875 +0100
@@ -581,7 +581,7 @@
 libcurl=no
 AC_ARG_WITH(curl,   [  --with-curl[=DIR]    curl install directory (default=auto)],
             [], [with_curl=auto])
-if test "x$with_curl" != "xno"; then
+if test "x$with_curl" = "xno"; then
   :
 elif test "x$with_curl" != "xauto"; then
   OCPPFLAGS="$CPPFLAGS"
@@ -639,7 +639,7 @@
 libexpat=no
 AC_ARG_WITH(expat,   [  --with-expat[=DIR]    expat install directory (default=auto)],
             [], [with_expat=auto])
-if test "x$with_expat" != "xno"; then
+if test "x$with_expat" = "xno"; then
        :
 elif test "x$with_expat" != "xauto"; then
   OCPPFLAGS="$CPPFLAGS"

**Comment by dinhviethoa** [comment]
Fixed with 43df0309f406ab92a08c6294f4d4f2b735e36379.
