### ISSUE TITLE
Fallback to TLSv1

### ISSUE THREAD

**Issue by timog24** [dinhviethoa/libetpan#226]
Using libetpan with Claws-mail on Archlinux:
Connecting to an imap server using Starttls the application falls back to TLSv1 even when TLSv1.1 and TLSv1.2 are available.

This has been tested with different servers/providers.

The bug has been traced back to libetpan by Claws developers: http://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=3622

libetpan Version: 1.6-2

**Comment by dinhviethoa** [comment]
Could you provide more details? Is it using OpenSSL or GnuTLS?
Also, let me know if you know how to fix it.

**Comment by timog24** [comment]
The application is using gnutls 3.4.9-1

I tested the behavior of different mail clients, including evolution which uses gnutls as well and the all connected using TLSv1.2. Claws was the only one having this issue. So it doesn't seem to be an issue with gnutls.

No idea on how to fix this.

**Comment by eworm-de** [comment]
Claws uses `gnutls`, but `libetpan` is linked against `openssl`:
```
% objdump -p /usr/lib/libetpan.so.17.1.0 | grep NEEDED | 
  NEEDED               libsasl2.so.3
  NEEDED               libssl.so.1.0.0
  NEEDED               libcrypto.so.1.0.0
  NEEDED               libz.so.1
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libc.so.6
  NEEDED               libgcc_s.so.1
```
There is `libssl.so.1.0.0` and `libcrypto.so.1.0.0`, but nothing regarding `libgnutls.so`.

**Comment by dinhviethoa** [comment]
Can someone try the following implementation below in mailstream_ssl.c?

```
static struct mailstream_ssl_data * ssl_data_new(int fd, time_t timeout,
	void (* callback)(struct mailstream_ssl_context * ssl_context, void * cb_data), void * cb_data)
{
  return ssl_data_new_full(fd, timeout, TLS_client_method(), callback, cb_data);
}

static struct mailstream_ssl_data * tls_data_new(int fd, time_t timeout,
  void (* callback)(struct mailstream_ssl_context * ssl_context, void * cb_data), void * cb_data)
{
  return ssl_data_new_full(fd, timeout, TLS_client_method(), callback, cb_data);
}
```

And let me know if everything still works?
with STARTTLS and full TLS connection?

Thanks!

**Comment by eworm-de** [comment]
@timog24, where do you see what TLS version claws-mail uses? Or do you read server logs?

**Comment by timog24** [comment]
I captured the traffic on my client with wireshark (using the newest version, the older ones don't display it clearly)

**Comment by eworm-de** [comment]
For me it looks like TLSv1.2 is being used:
![screenshot_2016-03-09_10-32-35](https://cloud.githubusercontent.com/assets/970853/13631664/27f391ae-e5e6-11e5-8985-c2029cfa86f0.png)

**Comment by timog24** [comment]
Still the same with my setup. Remember this only happens when you connect with Starttls

The only difference between our setup seems to be the port. I am using port 143 and you are using port 993 (which is usually for mandatory SSL/TLS and not Starttls)

![tls](https://cloud.githubusercontent.com/assets/17692260/13637065/a7df4fd8-e605-11e5-8c71-97b8a3c0aa43.jpg)

**Comment by eworm-de** [comment]
Ups, my fault... Thought all my accounts are set up to connect via STARTTLS. Indeed they were not.

You are right, STARTTLS does use TLSv1.

**Comment by eworm-de** [comment]
@timog24, want to try with a05064c?
Or do you want binary package?

**Comment by eworm-de** [comment]
Just install with:
```
pacman -U http://mirror.mylinuxtime.de/arch/eworm/x86_64/libetpan-1.6-3.1-x86_64.pkg.tar.xz
```

**Comment by timog24** [comment]
Works fine.

Thanks for the quick response

**Comment by eworm-de** [comment]
@timog24, can you please verify that things work with 7f1f97f?
```
pacman -U http://mirror.mylinuxtime.de/arch/eworm/x86_64/libetpan-1.6-3.2-x86_64.pkg.tar.xz
```

**Comment by timog24** [comment]
The new patch seems to work as well
