### ISSUE TITLE
Windows binary build

### ISSUE THREAD

**Issue by larisa-al** [dinhviethoa/libetpan#238]
Hello.
First of all I'm very new to libetpan and I'm using the .dll already built for Windows, so I haven't been involved with the source code.

I am working on a QtProject which uses libetpan for Windows and OS X.
For Windows I'm using the binary build downloaded from the URL provided http://d.etpan.org/mailcore2-deps/libetpan-win32/
And it works on receiving emails by imap, even with attachment. 
Sadly for sending mails by smtp: the attachment part doesn't completely work for me. The email is sent with subject, recipients and with mimetype and filename set correctly, there is even a file attached, but the file is **empty**.
![screen shot 2016-04-01 at 4 50 49 pm](https://cloud.githubusercontent.com/assets/17502339/14222791/ed024030-f829-11e5-81d4-f8586b6ce47e.png)
 
I know I'm not providing any code, but the tricky part is that on OS X the attachments are sent perfectly good and my search has lead me to think that maybe is caused by the *char filename part on 
`int mailmime_set_body_file(struct mailmime * build_info,
               char * filename)` on `mailmime_types_helper.c`
I use this filename `"C:\filenamehere"`.

So I thought that maybe it could be an issue you have seen before.
Thanks in advance.

**Comment by dinhviethoa** [comment]
Can you read the content of the file and add the data as attachment instead of referencing only the filename?
