### ISSUE TITLE
Is the code UTF-8 clean?

### ISSUE THREAD

**Issue by CTMacUser** [dinhviethoa/libetpan#245]
RFC 6532 describes a Unicode extension to the Internet Message Format. Unicode, in UTF-8 format, is allowed in all basic character types except for header field names (which remain as ASCII). Does the current code work with such characters in strings? For example, parsing a quoted pair needs to check if the byte after the backslash is a single ASCII character of if multiple bytes need to be considered.

**Comment by dinhviethoa** [comment]
There are lots of assumption that by the default charset is iso-8859-1 if there are non-ascii chars.
I'm not sure it's easy to support it.

**Comment by CTMacUser** [comment]
The base text used for Internet Messages is ASCII, with the fate of post-ASCII byte values unspecified. Taking a quick look at the files in [the low-level code section](https://github.com/dinhviethoa/libetpan/tree/master/src/low-level/imf), it seems that you just pass said characters values through as if they're valid. This is what the RFC specifies too.

As you do nothing else with those values, the code should be clean. This should be true as long as any string passing is done in whole pieces; possible problems could occur if you split a string anywhere.  (I didn't see this.)  String-splitting is the only place where you would have to check for the start (or end) of a UTF-8 sequence.  You're safe if you split strings at a boundary with a parse-significant character, since they're all ASCII.

You also have to watch when converting the strings to a Apple-based API, like CFString or NSString (for example, for MailCore2).  Then you have to try UTF-8 first, then ISO Latin-1 if the former fails.

**Comment by dinhviethoa** [comment]
Could you try to make the changes and see how it impacts the unit tests?
