### ISSUE TITLE
use only x.y versions or change build system to support x.y.z versions

### ISSUE THREAD

**Issue by mones** [dinhviethoa/libetpan#256]
Already commented on #249, but since it was closed I guess it slipped between the cracks, so let's stress it a bit:

The latest release is tagged 1.7.2 but make dist is generating a 1.7 tarball:

`-rw-r--r-- 1 devel devel 1306720 Jun 8 12:20 libetpan-1.7.tar.gz`

This, by itself, it's not a real problem, since I can repackage and rename the tarball to 1.7.2. Nevertheless, I've noticed that build system doesn't support micro versions at all, so, for example running libetpan-config --version echoes just 1.7 instead 1.7.2, which would be expected now.

If, for example, tomorrow a 1.7.3 is released, it will still say it's 1.7, which doesn't look good for any program trying to rely on libetpan version.

So, the options are clear. The easy one: just increase minor version when API changes (for this one 1.8 instead of 1.7.2) or, a bit more work: add support for micro versions in configure.ac.

Thanks in advance,

**Comment by mones** [comment]
Hi there Hoà!

Any thought about this?
Have you decided which option would you prefer?

best regards,

**Comment by dinhviethoa** [comment]
Could you submit a pull request to support x.y.z?

**Comment by mones** [comment]
Wow, that was fast ;-)
Thanks!
