### ISSUE TITLE
Google AppAuth Support

### ISSUE THREAD

**Issue by wyllys66** [dinhviethoa/libetpan#267]
Current Oath2 code fails with new Google AppAuth APIs.  Google is deprecating the old oath2 APIs and is encouraging devs to migate to AppAuth.  The libetpan oath2 support fails with AppAuth oath2 tokens.

**Comment by dinhviethoa** [comment]
Could you be more specific about which part of the code has an issue?

**Comment by wyllys66** [comment]
Im trying to debug it now, Im not exactly sure where the problem is.

I switched my app to use the new GTMAppAuth API from google (https://github.com/google/GTMAppAuth), and I can authenticate and get a token, but when I pass the token along to Mailcore by setting the OAuth2Token field in the session, it gets rejected when I try to send an email (yes, I did add the gmail.send to the scope in the original token request).  Using the older GTMOauth2  method works fine, but Google is encouraging developers to migrate to the new GTMAppAuth method in iOS.

**Comment by wyllys66** [comment]
OK, its not a libetpan or MailCore issue.  When sending through a gmail account with OAuth2, you have to request the entire gmail scope ("https://mail.google.com") when you get your token and not just the "gmail.send" scope (https://www.googleapis.com/auth/gmail.send").  Once I fixed that, it worked.
