### ISSUE TITLE
Not able to build in windows VS-2013:  'mailimf_fws_atom_for_word_parse' : must have external linkage in order to be exported/imported

### ISSUE THREAD

**Issue by wyankush** [dinhviethoa/libetpan#282]
hi,

I am getting the following error while building libetpan for windows:

c:\work\libetpan\src\low-level\imf\mailimf.c(1179): error C2201: 'mailimf_fws_atom_for_word_parse' : must have external linkage in order to be exported/imported.

**Comment by stringarray** [comment]
Downloaded 1.7.2 source, tried building it with Visual Studio 2015, it throws same error: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2201
after editing the code in src\low-level\imf\mailimf.c line 1177 by removing “static” identifier, it builds correctly.
1.8 source causes a lot more errors, please do not lose Visual Studio 2015 compatibility.

**Comment by dinhviethoa** [comment]
Could you please send a pull request to fix all the breakage?
I don't have a windows OS handy. Thanks!

**Comment by eesheesh** [comment]
I didn't check 1.8, but head builds ok on VS2013, VS2015, and VS2017 after the changes I made in PR #295.
