### ISSUE TITLE
Multiple OR query 

### ISSUE THREAD

**Issue by lastMove** [dinhviethoa/libetpan#287]
Hello, 

Thanks for this great library.
I would like to know what is the best way, using Libetpan to do an imap search query, using more than 2 OR Operand. 
For example I would like to search for subjects containing (foo or bar or fubar)

**Comment by dinhviethoa** [comment]
You can do `(or (or a b) c)`.

**Comment by lastMove** [comment]
Ok thanks That's what I did.
