### ISSUE TITLE
problem/solution returning user certificate

### ISSUE THREAD

**Issue by celane** [dinhviethoa/libetpan#288]
Claws-mail failed SSL handshake when a 'user certificate' was made available (claws-mail 3.15.1, libetpan 1.7.2, gnutls 3.5.16, fedora 26). Tracing the error messages (and using gdb) showed that a callback to mailstream_gnutls_client_cert_cb was not setting "cert_type", and incorrectly setting "key_type". 

This looks like a problem from the change of gnutls 3.0 api.  A small patch to fix this is attached; tested with claws-mail and it works for a .pem user certificate/private key.  

Note that gnutls_certificate_type_get is used to get the "cert_type", but there doesn't seem to be a similar call for getting the key_type, and the type is hidden inside an internal struct. So just set the key_type to X509, since that's the type that is being imported. 
[libetpan-CEL-20180211.patch.txt](https://github.com/dinhviethoa/libetpan/files/1714962/libetpan-CEL-20180211.patch.txt)

**Comment by dinhviethoa** [comment]
Could you create a pull request for libetpan? Thanks!
