### ISSUE TITLE
time for new release?

### ISSUE THREAD

**Issue by pmetzger** [dinhviethoa/libetpan#298]
A couple of bugs that have been fixed (like #290 and #292) since the last release seem important enough that maybe a new one would be a good idea?

**Comment by rosset** [comment]
bump

**Comment by dinhviethoa** [comment]
Hurray!
https://github.com/dinhviethoa/libetpan/releases/tag/1.9

**Comment by pmetzger** [comment]
Thanks for doing this! That said, the version number didn't get bumped...
