### ISSUE TITLE
Fix Travis build...

### ISSUE THREAD

**Issue by pmetzger** [dinhviethoa/libetpan#304]
1. Travis seems to currently be failing (see: https://travis-ci.org/dinhviethoa/libetpan )
2. I note that the .travis.yml file specifies only a single build on a fairly old version of Xcode. It would probably be a good idea to get builds on several versions of MacOS as well as Linux.

**Comment by dinhviethoa** [comment]
Would you be able to send a pull request to fix it? Thanks!

**Comment by pmetzger** [comment]
I could, but I might not get to it for a bit.

**Comment by dinhviethoa** [comment]
It's all fixed now.
