### ISSUE TITLE
1.9 version says 1.8

### ISSUE THREAD

**Issue by wwp** [dinhviethoa/libetpan#305]
$ libetpan-config --version
1.8.0

and in fact in libetpan_version.h:
#define LIBETPAN_VERSION_MINOR 8

**Comment by wwp** [comment]
Also, configure.ac:
m4_define([min_version], [8])

**Comment by pmetzger** [comment]
Yah, maybe we need a v1.9.1 release. :|

**Comment by dinhviethoa** [comment]
Could you check that everything is alright with https://github.com/dinhviethoa/libetpan/releases/tag/1.9.1
Thanks!
