### ISSUE TITLE
outdated openssl accepted by configure

### ISSUE THREAD

**Issue by olafhering** [dinhviethoa/libetpan#308]
It looks like openssl 0.9.8, as included in SLE11, does not provide the string '_STACK' that is expected after commit fffaadd2d6861439d3f84bdd858909f1d62015fc

**Comment by pmetzger** [comment]
@olafhering Maybe do a pull request with a patch to fix this?

**Comment by dinhviethoa** [comment]
Late to the party but I would love a pull request!

**Comment by olafhering** [comment]
Well, perhaps just do not care about stale openssl versions anymore. The distributions carrying those stale versions are stale as well.
