### ISSUE TITLE
Consider migrating build flags discovery to pkg-config

### ISSUE THREAD

**Issue by mones** [dinhviethoa/libetpan#317]
Hi Hoa,

The use of scripts like libetpan-config for providing build flags does not work well with multi-arch systems. There's a standard alternative pgk-config¹, which ease discovery of build flags and is multi-arch friendly. These files are as easy to write², are fully supported by autotools and are less prone to errors than custom scripts.

Thanks in advance and best regards!

¹ https://www.freedesktop.org/wiki/Software/pkg-config/
² See https://git.claws-mail.org/?p=claws.git;a=blob;f=claws-mail.pc.in for example, and configure.ac and Makefile.am on how to generate the pc file from it.

**Comment by AlexKYou** [comment]
Hi mones, 

I have created a pull request for migrating build flags discovery to pkg-config: 
https://github.com/dinhviethoa/libetpan/pull/324

If you could please review this, it would be much appreciated.

**Comment by mones** [comment]
Thanks @AlexKYou!

At first sight looks mostly OK, except for the "-letpan @LIBSUFFIX@" in libetpan.pc.in, which has an extra space not present on the original libetpan-config.in.

This will make build faild when @LIBSUFFIX@ is different from an empty string, since it's not a valid flag but a suffix, as its name implies.

**Comment by AlexKYou** [comment]
Thank you for pointing that out @mones!

 I have created another pull request for the fix: 
#325
