### ISSUE TITLE
mailimap_logout return MAILIMAP_ERROR_STREAM for no reason

### ISSUE THREAD

**Issue by Dan-Fraser** [dinhviethoa/libetpan#326]
Hello DinhVietHoa,

The libetpan library has been very helpful to us over at https://github.com/linuxmagic, however there seems to be an issue in the latest versions with mailimap_logout. The version that exists on Ubuntu 14.04 (Trusty) doesn't seem to have this issue, but the newer versions do.

We over at LinuxMagic would be happy to build a patch for this issue, but we are unsure why the issue is occurring and hopefully you could help us out.

The code we are using to test is:

```
#include <stdio.h>
#include <libetpan.h>

int main(int argc, char *argv[])
{
    mailimap *imap = mailimap_new(0, NULL);
    int r = 0;
    if (!imap) {
        return 1;
    }
    if ((r = mailimap_socket_connect(imap, "127.0.0.1", 143)) != MAILIMAP_NO_ERROR_NON_AUTHENTICATED) {
        printf("Failed to connect: %d\n", r);
        return 1;
    }
    if ((r = mailimap_login(imap, "postmaster@linuxmagic.dev", "asdfgh")) != MAILIMAP_NO_ERROR) {
        printf("Failed to login: %d\n", r);
        return 1;
    }
    if ((r = mailimap_select(imap, "INBOX")) != MAILIMAP_NO_ERROR) {
        printf("Failed to select: %d\n", r);
        return 1;
    }
    if ((r = mailimap_logout(imap)) != MAILIMAP_NO_ERROR) {
        printf("Failed to logout: %d\n", r);
        return 1;
    }
    mailimap_free(imap);
    return 0;
}
```

This is of course being used to test against our local Dovecot server with the given test credentials, the dovecot server is functioning as intended but for some reason we always receive:

```
Failed to logout: 4
```

Indicating the mailimap_logout function returned: MAILIMAP_ERROR_STREAM

After digging further into this issue I have narrowed it down to a block inside mailimap_response_parse_progress():
```
  if (r == MAILIMAP_NO_ERROR) {
    for(iter = clist_begin(cont_req_or_resp_data_list) ; iter != NULL ; iter = clist_next(iter)) {
      struct mailimap_cont_req_or_resp_data * cont_req_or_resp_data = clist_content(iter);
      if (cont_req_or_resp_data->rsp_type != MAILIMAP_RESP_RESP_DATA) {
        continue;
      }
      if (cont_req_or_resp_data->rsp_data.rsp_resp_data->rsp_type == MAILIMAP_RESP_DATA_TYPE_COND_BYE) {
        res = MAILIMAP_ERROR_STREAM;
        goto free_list;
      }
    }
  }
```

It seems that after parsing the "BYE" response this block of logic walks all of the response codes and checks for any with MAILIMAP_RESP_DATA_TYPE_COND_BYE, which is exactly the condition set when parsing the response to LOGOUT.

So it immediately sets res to MAILIMAP_ERROR_STREAM and jumps to free_list.

We are unsure about the purpose of this block of code so it is hard for us to develop a patch which mitigates this problem without possibly causing regression or introducing other bugs.

We can confirm that removing the block of code which assigns MAILIMAP_ERROR_STREAM to the result appears to bypass the issue and mailimap_logout no longer returns an error, however I am unsure about whether this has broken other features/mechanisms in the process.

We have also tested the same code against a Courier IMAP server and were met with the exact same results.

We would be happy to implement the fix but we need to know the purpose of the block of code that is setting the result to MAILIMAP_ERROR_STREAM.

**Comment by dinhviethoa** [comment]
The reason why it's a MAILIMAP_ERROR_STREAM is because it's indicating that the connection is closing.

See https://tools.ietf.org/html/rfc3501#section-7.1.5

Maybe we should special case the LOGOUT situation. You could put the response parser in a special logout mode by passing a parameter is_logout and and pass it down where needed.

Though, you could also ignore that particular error when using mailimap_logout().

Please send a pull request if you can since I won't be able to get it to it soon.

Thanks!

**Comment by Dan-Fraser** [comment]
Oh so that is intended behaviour.

I thought that code was trying to catch server responding BYE to a command that it wasn't supposed to, and indicating there was a stream error because of it.

I think I will just ignore that error from mailimap_logout() for now.

Thanks again for taking time to reply.

**Comment by dinhviethoa** [comment]
It’s not great that mailimap_logout() returns an error though.
I think it went unnoticed all those years :)

**Comment by Dan-Fraser** [comment]
Will look into creating a patch + pull request for you :)

Do you think best way is to pass flag in to parser to expect the BYE response?

Or maybe mailimap_logout() can just detect parser error MAILIMAP_ERROR_STREAM and return MAILIMAP_NO_ERROR?

**Comment by dinhviethoa** [comment]
Having mailimap_logout() detect the réponse sounds like a good enough approach to me.

Thanks!

**Comment by Dan-Fraser** [comment]
I have made a pull request for this patch here:

https://github.com/dinhviethoa/libetpan/pull/327

If there's any issues let me know, cheers.
