### ISSUE TITLE
I'd like to report a security vulnerability, but don't know how.

### ISSUE THREAD

**Issue by duesee** [dinhviethoa/libetpan#385]
Should I write an email to someone or just open an issue here? I suggest to also create a security policy (https://github.com/dinhviethoa/libetpan/security) here to help future reporters :-)

**Comment by dinhviethoa** [comment]
You can just open an issue here. I’ll take care of it. Thanks.

**Comment by duesee** [comment]
Okay, thanks. I will report it tomorrow then.
